server:
  port: 8000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
mybatis-plus:
  configuration:
    # 关闭二级缓存
    cache-enabled: false
    # 设置本地缓存作用域
    local-cache-scope: SESSION
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
spring:
  freemarker:
    check-template-location: false
  profiles:
    # 激活的环境，如果需要 quartz 分布式支持，需要修改 active: dev,quartz
    active: dev
  data:
    redis:
      repositories:
        enabled: false
#  pid:
#    file: /自行指定位置/eladmin.pid

  redis:
    #数据库索引
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间
    timeout: 5000

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/秒
code:
  expiration: 300

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCDU+SCfYhcac6zpdOazbDDedBDtzLE8vDBYO/WUQCmjpBysg/dCeIUTqhUjQpK/WoKVvI3Gk0mwI/4q6sj0DcbeHJwqX/4qsJhebux/2FdfiIHFuHUZpsi+GEfR4LrK/NYznHFhG6j94cVqO+dd+XjbZOVvAIRrza5eEFeC5/SThQMCEzQvfMlh/SMRRF40nId4PaDbsRAboOtyszXgyK7vABtt3kUg0Ot27fj1BumEdJJ8rqiTtIfYQvtd2FvC9+K3Mn7iDvfwXEAp+/lNvfq/rDRge+jLHIxwnvb2cfmOijGcr7WHY26CimOvr0kZpbPY/73PppbFtbaZoOWZ8FtAgMBAAECggEAS0gL9cGAKXl9w/2LD3JZobRybl7V+5BH8pJe6bwFY3TV2Om5rju8HWf5ln5DKDmcT9EHiA7Lqys3XJULxbvV2ylwcKS5dxJr2vStY5vBdJaZavby/Y7T33gCNKwJoEXReVbeYRtJUTTTetcchGf2oChwMaVUik6mUCtfTUnck/DZyaWAQ1kuRvSuGuzYYANvgS+E3ShpJmJEcEpyc9tNn+Tr4t6a3okkRwnNp3Zb0EFKnq0WhjzJAEyjTZh4LVPQSw4r0vg8M+FE8ynkF/k0GPYA9aQapbMf1f1klE3nA9eTmaB3emL0imBkPkHeB6p7UrNsFpyT5VYihnPZIFNNAQKBgQDSyxSDcec2tluFXH/RTUR7rPz6r4u9h35p6QapXR9TmB/MwjLuCEWf8wk3+7sOyondy1hMrO4JCYAP0ApRm3yARhxQwzpeUY/0cuMwwWMPE7kq2Cm9Rx1HI4ThUNiGvoGKSGZv+JOfvZAWczgf8ijRqmr4317MOjA2mgPEf6FjbwKBgQCffgNrU8M1dJrYnsvhAl7Bo7Rn5eUp8m1pA+bKhaKZh5KG6j83VUNKNzzFWXXrquyDwkH4us6VNSG5NeCX2uRuUn/9ksVB/2Hxus4uxdz8V6OMN+SD2LHNOoZ412rTkbT4bt2G8PvfSRcx3ObNikdYInlABz4nFUaElNb5ZBnK4wKBgHeyyEhIAvLHpLrbJt3UkaHlPpaf3qtWaIt9vsGn1qUiilQ8pq0SV28XlFGNCdDBZH5k/RQ1Usog8e6IxYNH1vAEYAnggqGSkTtPjgFen4CtQ4W30CPiYRbHbaqAvSPuxCKhMEI/Fp0sCMkmzmUdnt5IdowyU2OHW192H9OSYjPTAoGAFVuCibTFxzq+IZPiKVdv6O5LEj6u2VclX5KuLSCIDZch//8OSBKa2C1dbe/04oIY+evhebVKRKDAy1RzpuIhBMT3brVgxN219/DT+19zoDb8J6K0bxNte9YCe9wc6gfw+/Ocpp1OnS/kc0Dph0ylESBMrE5L/F/U+ZwUzYCiE5ECgYEArHqEj6p0VtZ7f8g8pAUIv4qEFYtiHoVhNGsh2/ow3Qxiz/8ch/s/HlriAwvZWqAEtBtYnL3qJPktnkp+bAUMmIl3bwvB70z2e2bevlLAgj/8C1oGqPdGygLV1ZYXkvDYtM0eRYijR4oVc+fxKiLX1o+wHR35kXs6pCk5Cjbal6U=
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg1Pkgn2IXGnOs6XTms2ww3nQQ7cyxPLwwWDv1lEApo6QcrIP3QniFE6oVI0KSv1qClbyNxpNJsCP+KurI9A3G3hycKl/+KrCYXm7sf9hXX4iBxbh1GabIvhhH0eC6yvzWM5xxYRuo/eHFajvnXfl422TlbwCEa82uXhBXguf0k4UDAhM0L3zJYf0jEUReNJyHeD2g27EQG6DrcrM14Miu7wAbbd5FINDrdu349QbphHSSfK6ok7SH2EL7XdhbwvfitzJ+4g738FxAKfv5Tb36v6w0YHvoyxyMcJ729nH5jooxnK+1h2Nugopjr69JGaWz2P+9z6aWxbW2maDlmfBbQIDAQAB